version: '3'

services:
  master:
    image: 'mariadb-node:0.2'
    ports:
      - '3306'
    environment:
      - SSH_ROOT_PASSWORD=1234
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_USER=slipp
      - MARIADB_PASSWORD=slipp_1234
      - MARIADB_DATABASE=slipp_study
  slave:
    image: 'mariadb-node:0.2'
    ports:
      - '3306'
    depends_on:
      - master
    environment:
      - SSH_ROOT_PASSWORD=1234
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_MASTER_HOST=master
      - MARIADB_MASTER_PORT=3306
      - MARIADB_MASTER_ROOT_PASSWORD=1234
      - MARIADB_USER=slipp
      - MARIADB_PASSWORD=slipp_1234
      - MARIADB_DATABASE=slipp_study
  mha:
    image: 'mariadb-manager:0.2'
    depends_on:
      - slave
    environment:
      - SSH_ROOT_PASSWORD=1234
    entrypoint:
      tail -f /dev/null