version: '2'

networks:
  slipp-network:
    driver: bridge

services:
  mariadb-master:
    image: 'bitnami/mariadb:latest'
    networks:
      - slipp-network
    ports:
      - '3306'
    volumes:
      - ./data:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=master1234
      - MARIADB_USER=slipp_user
      - MARIADB_PASSWORD=slipp1234
      - MARIADB_DATABASE=slipp_study
  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    networks:
      - slipp-network
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=slave1234
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master1234
      - MARIADB_USER=slipp_user
      - MARIADB_PASSWORD=slipp1234
      - MARIADB_DATABASE=slipp_study